apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service-{{ .Values.env}}"
  labels:
    env  : {{ .Values.env}}
spec:
  selector:
    project: {{ .Release.Name }}
  ports:
    - name      : listener
      protocol  : TCP
      port      : 80  
      targetPort: 8080