replicaCount: 2
env: default
container:
  image: eu.gcr.io/terr-325411/rental
  tag: init
ingress:
    host:
      default: project-rental.net 
      dev: dev.project-rental.net
      prod: prod.project-rental.net